menu:
    Blog: /
    Archive: /archives/
    GitHub: https://github.com/aiellochan
    Rss: /atom.xml

favicon: /favicon.gif
logo: /favicon.gif

# Comment
# e.g disqus: seansun
disqus:
duoshuo:

# Analytics
# google-analytics:
ga: UA-65933410-1

# Copyright Infomation
startyear: 2015
