menu:
    Blog: /
    Archive: /archives/
    Category: /categories/
    GitHub: https://github.com/aiellochan
    Rss: /atom.xml

favicon: /favicon.gif
logo: /favicon.gif

# Comment
# e.g disqus: seansun
disqus: aielloblog
duoshuo:

# Analytics
# google-analytics:
ga: UA-113953113-1

# Copyright Infomation
startyear: 2018
